language: python
dist: trusty
sudo: false
install: true
python: 2.7

addons:
  apt:
    packages:
    - python-flake8

virtualenv:
  system_site_packages: true

cache:
  - apt

script:
  - ./checkstyle.sh
